/**
 * District Flowers - Delivery Calculator Config
 * Edit zones and neighborhoods here without touching the main HTML
 * Al Rawabi is the delivery hub (East Riyadh, between Exits 11–12)
 */

const DELIVERY_CONFIG = {
  // WhatsApp business number (country code + number, no + or spaces)
  whatsappNumber: "966562288177",
  // Back button URL (e.g. your main site or cart). Leave empty to hide.
  backUrl: "",

  // District Flowers Al Zoubair Ibn Al Awwam, Ar Rawabi – for distance calculation
  hubCoordinates: { lat: 24.695074, lng: 46.792129 },
  // Road distance factor (straight-line × factor ≈ driving distance in city)
  roadFactor: 1.3,
  // Riyadh bounding box for Nominatim (lon1,lat1,lon2,lat2) – restricts search to Riyadh
  riyadhViewbox: "46.4,24.4,47.2,25.4",

  standardDeliveryLabel: { ar: "توصيل عادي", en: "Standard Delivery" },
  timeSlots: [
    "10:00 AM – 1:00 PM",
    "1:00 PM – 4:00 PM",
    "9:00 PM – 12:00 AM",
  ],

  // Zones: fee in SAR, neighborhoods in that zone { en, ar }
  zones: [
    {
      fee: 15,
      range: "0–5 km",
      neighborhoods: [
        { en: "Al Rawabi", ar: "الروابي" },
        { en: "Al Nahdah", ar: "النهضة" },
        { en: "Al Rimal", ar: "الرمال" },
        { en: "Al Rayyan", ar: "الريان" },
        { en: "Al Nadhim", ar: "النظيم" },
        { en: "Al Manar", ar: "المنار" },
      ],
    },
    {
      fee: 20,
      range: "6–10 km",
      neighborhoods: [
        { en: "Al Yarmouk", ar: "اليرموك" },
        { en: "Ishbiliyah", ar: "إشبيلية" },
        { en: "Al Rawdah", ar: "الروضة" },
        { en: "Al Hamra", ar: "الحمراء" },
        { en: "Granada", ar: "غرناطة" },
        { en: "Al Naseem East", ar: "النسيم الشرقي" },
        { en: "Al Naseem West", ar: "النسيم الغربي" },
        { en: "Al Salam", ar: "السلام" },
        { en: "Al Khaleej", ar: "الخليج" },
        { en: "Al Andalus", ar: "الأندلس" },
        { en: "King Faisal", ar: "الملك فيصل" },
        { en: "King Abdullah", ar: "الملك عبدالله" },
        { en: "Al Quds", ar: "القدس" },
        { en: "Al Falah", ar: "الفلاح" },
        { en: "Ash Shuhada", ar: "الشهداء" },
        { en: "Al Qadisiyah", ar: "القادسية" },
        { en: "Al Munsiyah", ar: "المنصية" },
        { en: "Al Sharafeyyah", ar: "الشرفية" },
      ],
    },
    {
      fee: 30,
      range: "11–15 km",
      neighborhoods: [
        { en: "Al Rabwah", ar: "الربوة" },
        { en: "Olaya", ar: "العليا" },
        { en: "Al Malaz", ar: "الملز" },
        { en: "Al Murabba", ar: "المربع" },
        { en: "Al Sulimaniyah", ar: "السليمانية" },
        { en: "Al Wizarat", ar: "الوزارات" },
        { en: "Al Faruq", ar: "الفاروق" },
        { en: "King AbdulAziz", ar: "الملك عبدالعزيز" },
        { en: "Al Safa", ar: "الصفا" },
        { en: "Al Faisaliyah", ar: "الفيصلية" },
        { en: "Al Sulay", ar: "الصلي" },
        { en: "Qurtubah", ar: "قرطبة" },
        { en: "Al Marwah", ar: "المريوة" },
        { en: "Al Mursalat", ar: "المرسلات" },
        { en: "Jarir", ar: "جرير" },
        { en: "Al Zahra", ar: "الزهراء" },
        { en: "Al Mishal", ar: "المشعل" },
        { en: "Al Safarat", ar: "الصفارات" },
        { en: "Al Fayha", ar: "الفيحاء" },
        { en: "Umm Al Hamam East", ar: "أم الحمام الشرقي" },
        { en: "Umm Al Hamam West", ar: "أم الحمام الغربي" },
        { en: "Al Masani", ar: "المصانع" },
      ],
    },
    {
      fee: 35,
      range: "16–20 km",
      neighborhoods: [
        { en: "Al Yasmin", ar: "الياسمين" },
        { en: "Al Nakheel", ar: "النخيل" },
        { en: "Hittin", ar: "حطين" },
        { en: "Al Rahmaniyah", ar: "الرحمانية" },
        { en: "Al Narjis", ar: "النرجس" },
        { en: "Al Maather", ar: "المعذر" },
        { en: "Al Sahafa", ar: "الصحافة" },
        { en: "Al Aqiq", ar: "العقيق" },
        { en: "Al Muruj", ar: "المروج" },
        { en: "Al Mansourah", ar: "المنصورة" },
        { en: "Al Muhamadiyyah", ar: "المحمدية" },
        { en: "Al Wadi", ar: "الوادي" },
        { en: "Al Woroud", ar: "الورود" },
        { en: "Al Ghadir", ar: "الغدير" },
        { en: "Al Urayja", ar: "العريجاء" },
        { en: "Al Urayja West", ar: "العريجاء الغربية" },
        { en: "Shubra", ar: "شبرا" },
        { en: "Dhahrat Laban", ar: "ظهرة لبن" },
        { en: "Al Masif", ar: "المصيف" },
      ],
    },
    {
      fee: 40,
      range: "21–25 km",
      neighborhoods: [
        { en: "Al Thumama", ar: "الثمامة" },
        { en: "Diriyah", ar: "الدرعية" },
        { en: "KAFD", ar: "مدينة الملك عبدالله المالية" },
        { en: "Al Qirawan", ar: "القيروان" },
        { en: "Al Janadriyah", ar: "الجنادرية" },
        { en: "Al Hazm", ar: "الحزم" },
        { en: "Al Dar Al Baida", ar: "الدار البيضاء" },
        { en: "Irqah", ar: "عرقة" },
        { en: "Tuwaiq", ar: "طويق" },
        { en: "Al Badiah", ar: "البديعة" },
        { en: "Al Suwaidi", ar: "السويدي" },
        { en: "Sultanah", ar: "سلطانة" },
        { en: "Namar", ar: "نمار" },
        { en: "Al Aziziyah", ar: "العزيزية" },
        { en: "Al Manakh", ar: "المناخ" },
        { en: "Manfuhah", ar: "منفوحة" },
        { en: "Al Batha", ar: "البطحاء" },
        { en: "Ad Dirah", ar: "الديرة" },
        { en: "Utaiqah", ar: "عتيقة" },
        { en: "Al Bujairi", ar: "البجيري" },
        { en: "Al Khalideya", ar: "الخالدية" },
        { en: "Al Khuzama", ar: "الخزامى" },
        { en: "Al Jazirah", ar: "الجزيرة" },
        { en: "Al Raid", ar: "الرائد" },
        { en: "Al Rafiah", ar: "الرفيعة" },
        { en: "As Saadah", ar: "السعادة" },
        { en: "As Salhiyah", ar: "الصالحية" },
        { en: "Al Sinaiyah", ar: "الصناعية" },
        { en: "Al Mutamarat", ar: "المطاعم" },
        { en: "Al Maizilah", ar: "الميزلة" },
        { en: "Al Mughrizat", ar: "المغريات" },
        { en: "Al Maather North", ar: "المعذر الشمالي" },
        { en: "An Nada", ar: "الندى" },
        { en: "An Nafal", ar: "النفل" },
        { en: "An Namudhajiyah", ar: "النامذجية" },
        { en: "Al Hada", ar: "الهدا" },
        { en: "Al Wahah", ar: "الواحة" },
        { en: "Al Wisham", ar: "الوشام" },
        { en: "Al Yamamah", ar: "اليمامة" },
        { en: "Umm Salim", ar: "أم سليم" },
        { en: "Salah Ad Din", ar: "صلاح الدين" },
        { en: "Ghubairah", ar: "غبيرة" },
        { en: "Al Izdihar", ar: "الازدهار" },
        { en: "Al Iskan", ar: "الإسكان" },
        { en: "Al Awali", ar: "العوالي" },
        { en: "King Fahd", ar: "الملك فهد" },
        { en: "Al Taawun", ar: "التعاون" },
      ],
    },
    {
      fee: 45,
      range: "26–40 km",
      neighborhoods: [
        { en: "Al Malqa", ar: "الملقا" },
      ],
    },
  ],
};

if (typeof module !== "undefined" && module.exports) {
  module.exports = { DELIVERY_CONFIG };
}
